version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: utilityhubDB
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # 컨테이너를 지워도 데이터가 남도록 설정

  backend:
    build: ./backend
    container_name: utility-hub-backend
    restart: always
    environment:
      SPRING_AI_GOOGLE_GENAI_API_KEY: ${SPRING_AI_GOOGLE_GENAI_API_KEY}
      DB_DRIVER : ${DB_DRIVER}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: utility-hub-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend